[platformio]
default_envs = warn_ctrl

[env:warn_ctrl]
platform = espressif32@6.10.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    autowp/autowp-mcp2515@1.2.1
    adafruit/Adafruit NeoPixel@1.12.5
build_src_filter = +<warn_ctrl/>

[env:native]
platform = native
test_framework = unity
build_src_filter = -<*>
