if(NOT DEFINED INPUT_FILE OR NOT EXISTS "${INPUT_FILE}")
	message(FATAL_ERROR "Phase 2 evidence input is missing: ${INPUT_FILE}")
endif()
if(NOT DEFINED OUTPUT_FILE)
	message(FATAL_ERROR "Phase 2 evidence output was not specified.")
endif()

file(SHA256 "${INPUT_FILE}" digest)
string(TOLOWER "${digest}" digest)
string(LENGTH "${digest}" digest_length)
if(NOT digest_length EQUAL 64 OR NOT digest MATCHES "^[0-9a-f]+$")
	message(FATAL_ERROR "Phase 2 evidence SHA-256 is not 64 normalized hex digits.")
endif()

set(temporary_file "${OUTPUT_FILE}.tmp")
file(WRITE "${temporary_file}" "${digest}")
file(RENAME "${temporary_file}" "${OUTPUT_FILE}" RESULT rename_result)
if(rename_result)
	message(FATAL_ERROR "Could not publish Phase 2 SHA-256 evidence: ${rename_result}")
endif()
